[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Smoke tests
    regression: Regression tests
    dashboard: Dashboard module
    navigation: Navigation module
    billing: Bills and Credits module
    profile: Profile module
    owner: Owner portal module
    inspection: Inspection tests

addopts =
    --html=reports/final_regression.html
    --self-contained-html

testpaths =
    tests